# Generated by Django 5.1.2 on 2024-12-13 23:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_gasstation_delete_hotel"),
    ]

    operations = [
        migrations.RemoveField(model_name="gasstation", name="fuel_types",),
        migrations.RemoveField(model_name="gasstation", name="opening_hours",),
        migrations.RemoveField(model_name="gasstation", name="price_per_liter",),
        migrations.AddField(
            model_name="gasstation",
            name="current_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="gasstation", name="reviews", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gasstation",
            name="user_rating",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="gasstation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
