# Generated by Django 5.1.2 on 2024-12-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_gasstation_fuel_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="gasstation", name="created_at",),
        migrations.RemoveField(model_name="gasstation", name="updated_at",),
    ]
